# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0195bd701e284f08499286ffd063d76c111132a36ac6a9cba3ee546a38a2adc218b5b217f3531d9daa7d06311f92d5f9a5e38db3333a348db0a45f762452024b

test:
  secret_key_base: 599c460553d7b56076e4dc1c2a5f5eae47613fc02d25617d3cb9a6e6dbf4d6c7c13bdcab40244360cdb9a16621ff69152614ba557e935aed58609c9303ce1ada

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
